<script lang="ts">
  import Heading from "$lib/components/v2/docs/Heading.svelte";
  import Subheading from "$lib/components/v2/docs/Subheading.svelte";
  import { PMCommand } from "$lib/components/ui/pm-command";
  import AlertCircle from "@lucide/svelte/icons/alert-circle";
</script>

<svelte:head>
  <title>Installation - Form Builder V2</title>
  <meta
    name="description"
    content="Install and set up Form Builder V2 dependencies in your SvelteKit project."
  />
</svelte:head>

<div class="mx-auto max-w-4xl px-6 py-8 pb-16">
  <Heading>Installation</Heading>
  <Subheading>
    Set up the required dependencies to use forms generated by Form Builder V2
    in your SvelteKit project.
  </Subheading>

  <div class="mt-12">
    <h2 class="text-xl font-semibold mb-4">Prerequisites</h2>
    <ul class="space-y-2 text-muted-foreground">
      <li class="flex gap-3">
        <span class="text-primary">•</span>
        <span>Node.js 18.0 or higher</span>
      </li>
      <li class="flex gap-3">
        <span class="text-primary">•</span>
        <span>SvelteKit 2.0 or higher</span>
      </li>
      <li class="flex gap-3">
        <span class="text-primary">•</span>
        <span>Package manager (npm, pnpm, yarn, or bun)</span>
      </li>
    </ul>
  </div>

  <div
    class="my-8 rounded-lg border border-blue-200 bg-blue-50 p-4 dark:border-blue-900 dark:bg-blue-950"
  >
    <div class="flex gap-3">
      <AlertCircle
        class="h-5 w-5 text-blue-600 dark:text-blue-400 shrink-0 mt-0.5"
      />
      <div class="text-sm text-blue-900 dark:text-blue-100">
        <p class="font-semibold mb-1">No Installation Needed</p>
        <p class="leading-relaxed">
          Form Builder V2 is a web-based tool. Visit <a
            href="/v2"
            class="underline hover:text-blue-700 dark:hover:text-blue-300"
          >
            the builder
          </a>, create your form, and copy the generated code. You only need to
          install dependencies in your project.
        </p>
      </div>
    </div>
  </div>

  <div class="mt-12">
    <h2 class="text-xl font-semibold mb-4">Core Dependencies</h2>
    <p class="text-muted-foreground mb-6 leading-relaxed">
      Install SvelteKit Superforms with your preferred validation library:
    </p>

    <div class="space-y-4">
      <div>
        <h3 class="text-base font-semibold mb-3">Using Zod</h3>
        <PMCommand command="add" args={["sveltekit-superforms", "zod"]} />
      </div>

      <div>
        <h3 class="text-base font-semibold mb-3">Using Valibot</h3>
        <PMCommand command="add" args={["sveltekit-superforms", "valibot"]} />
      </div>

      <div>
        <h3 class="text-base font-semibold mb-3">Using ArkType</h3>
        <PMCommand command="add" args={["sveltekit-superforms", "arktype"]} />
      </div>
    </div>
  </div>

 

  <div class="mt-12 rounded-lg border bg-muted/30 p-6">
    <h2 class="text-lg font-semibold mb-3">Next Steps</h2>
    <p class="text-muted-foreground leading-relaxed">
      After installing dependencies, head to the <a
        href="/v2"
        class="text-primary hover:underline"
      >
        Form Builder
      </a> to create your first form, or check the usage guide to learn about V2's
      features.
    </p>
  </div>
</div>
